name: Build and Deploy Angular App

on:
  push:
    branches: [ "master" ]   # run on pushes to main branch

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write


    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.CR_PAT }}

      # 3. Build and push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ghcr.io/${{ secrets.GH_USERNAME }}/angular-app:latest

          
# Deploy stage (on your Pi runner)
  deploy:
    stage: deploy
    tags:
      - arm64       # ensure this runs on your Pi
    script:
        # Stop container if running
      - |
          if [ "$(docker ps -q -f name=ghcr.io/saifeddine01/angular-app)" ]; then
            echo "Stopping existing container..."
            docker stop ghcr.io/saifeddine01/angular-app
            docker rm ghcr.io/saifeddine01/angular-app
          fi
        # Pull latest image
      - docker pull ghcr.io/saifeddine01/angular-app
        # Run new container
      - docker run -d --name ghcr.io/saifeddine01/angular-app -p 80:80 ghcr.io/saifeddine01/angular-app


