name: Build and Deploy Angular App

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.CR_PAT }}

      # 3. Build and push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          platforms: linux/arm64
          tags: ghcr.io/${{ secrets.GH_USERNAME }}/angular-app:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      # Stop existing container if running
      - name: Stop running container
        run: |
          CONTAINER_NAME=angular-app
          if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
            echo "Stopping existing container..."
            docker stop $CONTAINER_NAME
            docker rm $CONTAINER_NAME
          fi

      # Pull latest image
      # - name: Pull latest image
      #   run: docker pull ghcr.io/${{ secrets.GH_USERNAME }}/angular-app:latest

      # Run new container
      - name: Run container
        run: docker run -d --name angular-app -p 80:80 ghcr.io/${{ secrets.GH_USERNAME }}/angular-app:latest
